import { format, addDays, addMonths } from 'date-fns'
import type { Currency } from './fx'

export type OfferStatus = 'BOOKABLE' | 'ON_REQUEST' | 'SHOWCASE'

export interface Session {
  id: string
  startDate: string // ISO date
  endDate: string // ISO date
  price: number
  currency: Currency
  capacityTotal: number
  capacityRemaining: number
}

export interface DayProgram {
  day: number
  title: string
  description: string
  activities: string[]
  accommodation?: string
  meals: string[]
  image?: string
}

export interface Offer {
  id: string
  slug: string
  title: string
  destination: string
  country: string
  durationDays: number
  language: string[]
  status: OfferStatus
  departuresEligible: string[]
  images: string[]
  basePrice: number
  currency: Currency
  description: string
  included: string[]
  notIncluded: string[]
  cancellationPolicy: string
  sessions: Session[]
  program?: DayProgram[]
}

// Générer des dates futures pour les sessions
const now = new Date()
const nextMonth = addMonths(now, 1)
const twoMonthsLater = addMonths(now, 2)
const threeMonthsLater = addMonths(now, 3)

export const MOCK_OFFERS: Offer[] = [
  // Pèlerinages en Espagne - Camino de Santiago
  {
    id: '1',
    slug: 'camino-santiago-frances',
    title: 'Camino de Santiago - Chemin Français',
    destination: 'Santiago de Compostela',
    country: 'Espagne',
    durationDays: 35,
    language: ['Français', 'Espagnol', 'Anglais'],
    status: 'BOOKABLE',
    departuresEligible: ['Paris', 'Londres', 'Montréal'],
    images: [
      'https://picsum.photos/800/600?random=1',
      'https://picsum.photos/800/600?random=2',
    ],
    basePrice: 1200,
    currency: 'EUR',
    description: 'Parcourez le célèbre Chemin de Saint-Jacques-de-Compostelle depuis Saint-Jean-Pied-de-Port jusqu\'à la cathédrale de Santiago. Un pèlerinage spirituel de 800 km à travers les paysages magnifiques du nord de l\'Espagne. Hébergement en auberges de pèlerins, repas traditionnels, guide spirituel et support logistique.',
    included: [
      'Hébergement en auberges de pèlerins',
      'Petit-déjeuner quotidien',
      'Guide spirituel francophone',
      'Support logistique et bagages',
      'Crédencial (passeport du pèlerin)',
      'Assurance voyage de base',
    ],
    notIncluded: [
      'Vols internationaux',
      'Déjeuners et dîners',
      'Équipement de marche',
      'Assurance annulation',
    ],
    cancellationPolicy: 'Annulation gratuite jusqu\'à 60 jours avant le départ. Remboursement de 50% entre 60 et 30 jours. Aucun remboursement moins de 30 jours avant.',
    sessions: [
      {
        id: 's1',
        startDate: format(addDays(nextMonth, 1), 'yyyy-MM-dd'),
        endDate: format(addDays(nextMonth, 36), 'yyyy-MM-dd'),
        price: 1200,
        currency: 'EUR',
        capacityTotal: 20,
        capacityRemaining: 12,
      },
      {
        id: 's2',
        startDate: format(addDays(twoMonthsLater, 5), 'yyyy-MM-dd'),
        endDate: format(addDays(twoMonthsLater, 40), 'yyyy-MM-dd'),
        price: 1200,
        currency: 'EUR',
        capacityTotal: 20,
        capacityRemaining: 20,
      },
    ],
  },
  {
    id: '2',
    slug: 'camino-santiago-portugais',
    title: 'Camino Português - Chemin Portugais',
    destination: 'Santiago de Compostela',
    country: 'Espagne',
    durationDays: 12,
    language: ['Français', 'Portugais', 'Espagnol'],
    status: 'BOOKABLE',
    departuresEligible: ['Paris', 'Londres'],
    images: [
      'https://picsum.photos/800/600?random=3',
      'https://picsum.photos/800/600?random=4',
    ],
    basePrice: 850,
    currency: 'EUR',
    description: 'Le Chemin Portugais depuis Porto jusqu\'à Santiago. Un itinéraire plus court mais tout aussi riche spirituellement, traversant les charmants villages portugais et espagnols. Parfait pour un premier pèlerinage.',
    included: [
      'Hébergement en auberges et hôtels',
      'Petit-déjeuner',
      'Guide spirituel',
      'Crédencial',
      'Support logistique',
    ],
    notIncluded: [
      'Vols internationaux',
      'Repas (sauf petit-déjeuner)',
      'Équipement',
    ],
    cancellationPolicy: 'Annulation gratuite jusqu\'à 45 jours avant le départ.',
    program: [
      {
        day: 1,
        title: 'Arrivée à Porto',
        description: 'Accueil à l\'hôtel dans le centre historique de Porto. Réunion d\'information avec votre guide, remise de la crédencial et découverte de la magnifique ville de Porto.',
        activities: ['Accueil et installation', 'Réunion d\'information', 'Remise de la crédencial', 'Visite libre de Porto', 'Dîner de bienvenue'],
        accommodation: 'Hôtel dans le centre historique de Porto',
        meals: ['Dîner'],
        image: 'https://picsum.photos/800/600?random=201',
      },
      {
        day: 2,
        title: 'Porto → Vilarinho',
        description: 'Première étape du Chemin Portugais. Départ de Porto, traversée des quartiers historiques, puis marche le long du fleuve Douro vers Vilarinho.',
        activities: ['Départ de Porto', 'Traversée du centre historique', 'Marche le long du Douro', 'Arrivée à Vilarinho', 'Messe du pèlerin'],
        accommodation: 'Auberge à Vilarinho',
        meals: ['Petit-déjeuner', 'Déjeuner pique-nique', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=202',
      },
      {
        day: 3,
        title: 'Vilarinho → Barcelos',
        description: 'Marche à travers les paysages ruraux portugais, passage par des villages traditionnels. Arrivée à Barcelos, célèbre pour ses coqs colorés.',
        activities: ['Marche vers Barcelos', 'Villages portugais', 'Arrivée à Barcelos', 'Découverte de la ville', 'Temps de méditation'],
        accommodation: 'Auberge à Barcelos',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=203',
      },
      {
        day: 4,
        title: 'Barcelos → Ponte de Lima',
        description: 'Traversée de la région du Minho, connue pour ses vignobles. Arrivée à Ponte de Lima, la plus ancienne ville du Portugal.',
        activities: ['Traversée du Minho', 'Vignobles portugais', 'Arrivée à Ponte de Lima', 'Visite de la ville', 'Messe'],
        accommodation: 'Auberge à Ponte de Lima',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=204',
      },
      {
        day: 5,
        title: 'Ponte de Lima → Rubiães',
        description: 'Étape plus courte mais avec une montée vers Rubiães. Passage par des forêts de chênes et d\'eucalyptus.',
        activities: ['Montée vers Rubiães', 'Forêts portugaises', 'Arrivée à Rubiães', 'Prière du soir'],
        accommodation: 'Auberge à Rubiães',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=205',
      },
      {
        day: 6,
        title: 'Rubiães → Valença',
        description: 'Descente vers Valença, ville fortifiée à la frontière avec l\'Espagne. Vue magnifique sur le fleuve Minho et la ville espagnole de Tui.',
        activities: ['Descente vers Valença', 'Ville fortifiée', 'Frontière Portugal-Espagne', 'Vue sur Tui', 'Méditation'],
        accommodation: 'Hôtel à Valença',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=206',
      },
      {
        day: 7,
        title: 'Valença → Tui (Espagne)',
        description: 'Traversée du pont international vers l\'Espagne. Arrivée à Tui, première ville espagnole du chemin. Visite de la cathédrale.',
        activities: ['Traversée vers l\'Espagne', 'Arrivée à Tui', 'Visite de la cathédrale', 'Premier tampon espagnol', 'Messe'],
        accommodation: 'Auberge à Tui',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=207',
      },
      {
        day: 8,
        title: 'Tui → Redondela',
        description: 'Marche à travers la Galice espagnole, région verte et vallonnée. Passage par des villages galiciens typiques.',
        activities: ['Marche vers Redondela', 'Paysages galiciens', 'Villages typiques', 'Arrivée à Redondela', 'Temps de réflexion'],
        accommodation: 'Auberge à Redondela',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=208',
      },
      {
        day: 9,
        title: 'Redondela → Pontevedra',
        description: 'Continuation à travers la Galice, passage par des forêts et des zones côtières. Arrivée à Pontevedra, charmante ville historique.',
        activities: ['Marche vers Pontevedra', 'Forêts galiciennes', 'Zones côtières', 'Arrivée à Pontevedra', 'Visite de la ville'],
        accommodation: 'Auberge à Pontevedra',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=209',
      },
      {
        day: 10,
        title: 'Pontevedra → Caldas de Reis',
        description: 'Avant-dernière étape avant Santiago. Passage par des zones thermales, paysages verdoyants de Galice.',
        activities: ['Marche vers Caldas de Reis', 'Zones thermales', 'Paysages verdoyants', 'Arrivée à Caldas de Reis', 'Méditation'],
        accommodation: 'Auberge à Caldas de Reis',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=210',
      },
      {
        day: 11,
        title: 'Caldas de Reis → Padrón',
        description: 'Dernière étape avant Santiago. Passage par Padrón, lieu légendaire où la barque de Saint-Jacques aurait accosté.',
        activities: ['Marche vers Padrón', 'Lieu légendaire', 'Arrivée à Padrón', 'Préparation pour Santiago', 'Messe'],
        accommodation: 'Auberge à Padrón',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=211',
      },
      {
        day: 12,
        title: 'Padrón → Santiago de Compostela',
        description: 'Dernière étape ! Arrivée à Santiago de Compostela, montée des escaliers de la cathédrale, embrassade de la statue de Saint-Jacques, et célébration de la Messe du Pèlerin.',
        activities: ['Dernière marche vers Santiago', 'Arrivée à la cathédrale', 'Embrassade de Saint-Jacques', 'Messe du Pèlerin', 'Célébration et remise de la Compostela'],
        accommodation: 'Hôtel à Santiago de Compostela',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner de célébration'],
        image: 'https://picsum.photos/800/600?random=212',
      },
    ],
    sessions: [
      {
        id: 's3',
        startDate: format(addDays(nextMonth, 10), 'yyyy-MM-dd'),
        endDate: format(addDays(nextMonth, 22), 'yyyy-MM-dd'),
        price: 850,
        currency: 'EUR',
        capacityTotal: 15,
        capacityRemaining: 8,
      },
    ],
  },
  
  // Pèlerinages en Italie - Rome
  {
    id: '3',
    slug: 'pelerinage-rome-vatican',
    title: 'Pèlerinage à Rome et au Vatican',
    destination: 'Rome',
    country: 'Italie',
    durationDays: 7,
    language: ['Français', 'Italien', 'Anglais'],
    status: 'BOOKABLE',
    departuresEligible: ['Paris', 'Londres', 'New York'],
    images: [
      'https://picsum.photos/800/600?random=5',
      'https://picsum.photos/800/600?random=6',
    ],
    basePrice: 950,
    currency: 'EUR',
    description: 'Découvrez les sites sacrés de Rome : Basilique Saint-Pierre, Catacombes, Basilique Sainte-Marie-Majeure, et bien d\'autres. Visites guidées des lieux saints, audiences papales, messes dans les basiliques historiques.',
    included: [
      'Hébergement en hôtel 3 étoiles près du Vatican',
      'Petit-déjeuner',
      'Guide spirituel francophone',
      'Visites guidées des basiliques',
      'Transport sur place',
      'Assurance voyage',
    ],
    notIncluded: [
      'Vols internationaux',
      'Repas (sauf petit-déjeuner)',
      'Dépenses personnelles',
    ],
    cancellationPolicy: 'Annulation gratuite jusqu\'à 30 jours avant le départ.',
    sessions: [
      {
        id: 's4',
        startDate: format(addDays(nextMonth, 15), 'yyyy-MM-dd'),
        endDate: format(addDays(nextMonth, 22), 'yyyy-MM-dd'),
        price: 950,
        currency: 'EUR',
        capacityTotal: 25,
        capacityRemaining: 15,
      },
      {
        id: 's5',
        startDate: format(addDays(twoMonthsLater, 8), 'yyyy-MM-dd'),
        endDate: format(addDays(twoMonthsLater, 15), 'yyyy-MM-dd'),
        price: 980,
        currency: 'EUR',
        capacityTotal: 25,
        capacityRemaining: 25,
      },
    ],
  },
  {
    id: '4',
    slug: 'via-francigena-rome',
    title: 'Via Francigena - Chemin vers Rome',
    destination: 'Rome',
    country: 'Italie',
    durationDays: 28,
    language: ['Français', 'Italien'],
    status: 'ON_REQUEST',
    departuresEligible: ['Paris', 'Londres'],
    images: [
      'https://picsum.photos/800/600?random=7',
      'https://picsum.photos/800/600?random=8',
    ],
    basePrice: 1800,
    currency: 'EUR',
    description: 'Parcourez l\'ancienne route de pèlerinage Via Francigena depuis la Toscane jusqu\'à Rome. Un chemin historique emprunté par les pèlerins depuis le Moyen Âge, traversant des paysages toscans magnifiques.',
    included: [
      'Hébergement en auberges et hôtels',
      'Tous les repas',
      'Guide spirituel et historique',
      'Support logistique',
      'Testimonium (certificat de pèlerin)',
    ],
    notIncluded: [
      'Vols internationaux',
      'Équipement de marche',
    ],
    cancellationPolicy: 'Annulation gratuite jusqu\'à 45 jours avant le départ.',
    program: [
      {
        day: 1,
        title: 'Arrivée en Toscane - San Miniato',
        description: 'Accueil dans la région toscane, point de départ de la Via Francigena. Réunion d\'information, remise du Testimonium et préparation du départ.',
        activities: ['Accueil en Toscane', 'Réunion d\'information', 'Remise du Testimonium', 'Préparation', 'Dîner de bienvenue'],
        accommodation: 'Hôtel à San Miniato',
        meals: ['Dîner'],
        image: 'https://picsum.photos/800/600?random=601',
      },
      {
        day: 5,
        title: 'Traversée de la Toscane',
        description: 'Marche à travers les magnifiques paysages toscans : collines, vignobles, villages médiévaux. Passage par San Gimignano et ses tours.',
        activities: ['Paysages toscans', 'Villages médiévaux', 'San Gimignano', 'Vignobles', 'Messe'],
        accommodation: 'Auberge en Toscane',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=602',
      },
      {
        day: 10,
        title: 'Vers Sienne',
        description: 'Arrivée à Sienne, magnifique ville médiévale. Visite de la cathédrale et de la Piazza del Campo.',
        activities: ['Marche vers Sienne', 'Arrivée à Sienne', 'Visite de la cathédrale', 'Piazza del Campo', 'Messe'],
        accommodation: 'Hôtel à Sienne',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=603',
      },
      {
        day: 15,
        title: 'Traversée de l\'Ombrie',
        description: 'Continuation vers le sud, traversée de l\'Ombrie, région verdoyante au cœur de l\'Italie.',
        activities: ['Traversée de l\'Ombrie', 'Paysages verdoyants', 'Villages ombriens', 'Temps de méditation', 'Messe'],
        accommodation: 'Auberge en Ombrie',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=604',
      },
      {
        day: 20,
        title: 'Vers Viterbe',
        description: 'Arrivée à Viterbe, dernière grande ville avant Rome. Temps de repos et préparation pour l\'arrivée à Rome.',
        activities: ['Marche vers Viterbe', 'Arrivée à Viterbe', 'Temps de repos', 'Préparation pour Rome', 'Messe'],
        accommodation: 'Hôtel à Viterbe',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=605',
      },
      {
        day: 25,
        title: 'Approche de Rome',
        description: 'Dernières étapes avant Rome. Passage par les paysages du Latium, anticipation de l\'arrivée à la Ville Éternelle.',
        activities: ['Approche de Rome', 'Paysages du Latium', 'Anticipation', 'Temps de réflexion', 'Messe'],
        accommodation: 'Auberge près de Rome',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=606',
      },
      {
        day: 28,
        title: 'Arrivée à Rome - Basilique Saint-Pierre',
        description: 'Dernière étape ! Arrivée à Rome et à la Basilique Saint-Pierre. Remise du Testimonium, célébration et messe d\'action de grâce.',
        activities: ['Arrivée à Rome', 'Basilique Saint-Pierre', 'Remise du Testimonium', 'Messe d\'action de grâce', 'Célébration'],
        accommodation: 'Hôtel à Rome',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner de célébration'],
        image: 'https://picsum.photos/800/600?random=607',
      },
    ],
    sessions: [
      {
        id: 's6',
        startDate: format(addDays(twoMonthsLater, 1), 'yyyy-MM-dd'),
        endDate: format(addDays(twoMonthsLater, 29), 'yyyy-MM-dd'),
        price: 1800,
        currency: 'EUR',
        capacityTotal: 12,
        capacityRemaining: 5,
      },
    ],
  },

  // Pèlerinages en France - Lourdes
  {
    id: '5',
    slug: 'pelerinage-lourdes',
    title: 'Pèlerinage à Lourdes',
    destination: 'Lourdes',
    country: 'France',
    durationDays: 5,
    language: ['Français', 'Anglais'],
    status: 'BOOKABLE',
    departuresEligible: ['Paris', 'Londres', 'Montréal'],
    images: [
      'https://picsum.photos/800/600?random=9',
      'https://picsum.photos/800/600?random=10',
    ],
    basePrice: 450,
    currency: 'EUR',
    description: 'Découvrez le sanctuaire de Lourdes, lieu d\'apparitions mariales. Visites guidées de la grotte de Massabielle, processions aux flambeaux, bains dans les piscines, messes et temps de prière.',
    included: [
      'Hébergement en hôtel près du sanctuaire',
      'Petit-déjeuner',
      'Guide spirituel',
      'Visites guidées',
      'Transport depuis Paris',
    ],
    notIncluded: [
      'Repas (sauf petit-déjeuner)',
      'Dépenses personnelles',
    ],
    cancellationPolicy: 'Annulation gratuite jusqu\'à 15 jours avant le départ.',
    program: [
      {
        day: 1,
        title: 'Arrivée à Lourdes',
        description: 'Accueil à l\'hôtel près du sanctuaire. Installation et première découverte du domaine de la Grotte. Réunion d\'information avec votre guide spirituel.',
        activities: ['Accueil et installation', 'Découverte du sanctuaire', 'Réunion d\'information', 'Première visite de la Grotte', 'Dîner de bienvenue'],
        accommodation: 'Hôtel près du sanctuaire',
        meals: ['Dîner'],
        image: 'https://picsum.photos/800/600?random=401',
      },
      {
        day: 2,
        title: 'Grotte de Massabielle et Procession aux Flambeaux',
        description: 'Visite approfondie de la Grotte de Massabielle, lieu des apparitions de la Vierge Marie à Bernadette Soubirous. Participation à la Procession aux Flambeaux en soirée.',
        activities: ['Visite de la Grotte', 'Temps de prière à la Grotte', 'Découverte de l\'histoire', 'Procession aux Flambeaux', 'Messe'],
        accommodation: 'Hôtel près du sanctuaire',
        meals: ['Petit-déjeuner', 'Déjeuner libre', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=402',
      },
      {
        day: 3,
        title: 'Basiliques et Bains',
        description: 'Visite des Basiliques (Immaculée-Conception et Notre-Dame-du-Rosaire), puis possibilité de prendre les bains dans les piscines du sanctuaire.',
        activities: ['Basilique Immaculée-Conception', 'Basilique Notre-Dame-du-Rosaire', 'Bains dans les piscines', 'Temps de méditation', 'Messe'],
        accommodation: 'Hôtel près du sanctuaire',
        meals: ['Petit-déjeuner', 'Déjeuner libre', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=403',
      },
      {
        day: 4,
        title: 'Chemin de Croix et Maison de Bernadette',
        description: 'Parcours du Chemin de Croix sur l\'Espélugues, puis visite de la Maison natale de Bernadette Soubirous et du Moulin de Boly.',
        activities: ['Chemin de Croix', 'Maison natale de Bernadette', 'Moulin de Boly', 'Temps de réflexion', 'Messe'],
        accommodation: 'Hôtel près du sanctuaire',
        meals: ['Petit-déjeuner', 'Déjeuner libre', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=404',
      },
      {
        day: 5,
        title: 'Dernière visite et départ',
        description: 'Dernier temps de prière à la Grotte, messe d\'action de grâce, puis temps libre avant le départ.',
        activities: ['Dernière visite de la Grotte', 'Messe d\'action de grâce', 'Temps libre', 'Déjeuner libre', 'Départ'],
        accommodation: 'N/A',
        meals: ['Petit-déjeuner'],
        image: 'https://picsum.photos/800/600?random=405',
      },
    ],
    sessions: [
      {
        id: 's7',
        startDate: format(addDays(nextMonth, 5), 'yyyy-MM-dd'),
        endDate: format(addDays(nextMonth, 10), 'yyyy-MM-dd'),
        price: 450,
        currency: 'EUR',
        capacityTotal: 30,
        capacityRemaining: 18,
      },
      {
        id: 's8',
        startDate: format(addDays(twoMonthsLater, 12), 'yyyy-MM-dd'),
        endDate: format(addDays(twoMonthsLater, 17), 'yyyy-MM-dd'),
        price: 450,
        currency: 'EUR',
        capacityTotal: 30,
        capacityRemaining: 30,
      },
    ],
  },
  {
    id: '6',
    slug: 'chemin-compostelle-france',
    title: 'Chemin de Compostelle - Voie du Puy',
    destination: 'Saint-Jean-Pied-de-Port',
    country: 'France',
    durationDays: 30,
    language: ['Français'],
    status: 'ON_REQUEST',
    departuresEligible: ['Paris'],
    images: [
      'https://picsum.photos/800/600?random=11',
      'https://picsum.photos/800/600?random=12',
    ],
    basePrice: 1100,
    currency: 'EUR',
    description: 'Parcourez la Voie du Puy-en-Velay jusqu\'à Saint-Jean-Pied-de-Port, la section française du Chemin de Compostelle. Traversez les magnifiques paysages du Massif Central et des Pyrénées.',
    included: [
      'Hébergement en gîtes et auberges',
      'Petit-déjeuner',
      'Guide spirituel',
      'Crédencial',
      'Support logistique',
    ],
    notIncluded: [
      'Repas (sauf petit-déjeuner)',
      'Équipement',
    ],
    cancellationPolicy: 'Annulation gratuite jusqu\'à 60 jours avant le départ.',
    program: [
      {
        day: 1,
        title: 'Arrivée au Puy-en-Velay',
        description: 'Accueil au Puy-en-Velay, point de départ historique de la Voie du Puy. Réunion d\'information, remise de la crédencial et visite de la cathédrale Notre-Dame.',
        activities: ['Accueil au Puy-en-Velay', 'Réunion d\'information', 'Remise de la crédencial', 'Visite de la cathédrale', 'Dîner de bienvenue'],
        accommodation: 'Hôtel au Puy-en-Velay',
        meals: ['Dîner'],
        image: 'https://picsum.photos/800/600?random=701',
      },
      {
        day: 5,
        title: 'Traversée du Massif Central',
        description: 'Marche à travers les paysages volcaniques du Massif Central. Passage par des villages typiques de Haute-Loire.',
        activities: ['Paysages volcaniques', 'Massif Central', 'Villages typiques', 'Temps de méditation', 'Messe'],
        accommodation: 'Gîte en Haute-Loire',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=702',
      },
      {
        day: 10,
        title: 'Vers le Cantal',
        description: 'Continuation vers le Cantal, région montagneuse aux paysages magnifiques. Passage par des cols et des vallées.',
        activities: ['Région du Cantal', 'Cols et vallées', 'Paysages montagneux', 'Temps de réflexion', 'Messe'],
        accommodation: 'Gîte dans le Cantal',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=703',
      },
      {
        day: 15,
        title: 'Traversée de l\'Aveyron',
        description: 'Descente vers l\'Aveyron, passage par Conques et son abbaye, l\'un des plus beaux villages de France.',
        activities: ['Traversée de l\'Aveyron', 'Conques', 'Abbaye de Conques', 'Visite du village', 'Messe'],
        accommodation: 'Gîte à Conques',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=704',
      },
      {
        day: 20,
        title: 'Vers le Lot',
        description: 'Continuation vers le Lot, région aux paysages variés entre causses et vallées. Passage par Figeac.',
        activities: ['Région du Lot', 'Causses et vallées', 'Figeac', 'Temps de méditation', 'Messe'],
        accommodation: 'Gîte dans le Lot',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=705',
      },
      {
        day: 25,
        title: 'Approche des Pyrénées',
        description: 'Avant-dernière étape avant les Pyrénées. Passage par Moissac et son abbaye, puis préparation pour la traversée des montagnes.',
        activities: ['Approche des Pyrénées', 'Moissac', 'Abbaye de Moissac', 'Préparation', 'Messe'],
        accommodation: 'Gîte près des Pyrénées',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=706',
      },
      {
        day: 30,
        title: 'Arrivée à Saint-Jean-Pied-de-Port',
        description: 'Dernière étape ! Arrivée à Saint-Jean-Pied-de-Port, porte d\'entrée vers l\'Espagne et le Camino Francés. Célébration et préparation pour la suite du chemin.',
        activities: ['Arrivée à Saint-Jean-Pied-de-Port', 'Porte d\'entrée vers l\'Espagne', 'Célébration', 'Messe d\'action de grâce', 'Préparation pour l\'Espagne'],
        accommodation: 'Hôtel à Saint-Jean-Pied-de-Port',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner de célébration'],
        image: 'https://picsum.photos/800/600?random=707',
      },
    ],
    sessions: [
      {
        id: 's9',
        startDate: format(addDays(twoMonthsLater, 1), 'yyyy-MM-dd'),
        endDate: format(addDays(twoMonthsLater, 31), 'yyyy-MM-dd'),
        price: 1100,
        currency: 'EUR',
        capacityTotal: 15,
        capacityRemaining: 3,
      },
    ],
  },

  // Pèlerinages en Israël - Jérusalem
  {
    id: '7',
    slug: 'pelerinage-jerusalem-terre-sainte',
    title: 'Pèlerinage en Terre Sainte - Jérusalem',
    destination: 'Jérusalem',
    country: 'Israël',
    durationDays: 10,
    language: ['Français', 'Anglais', 'Hébreu'],
    status: 'BOOKABLE',
    departuresEligible: ['Paris', 'Londres', 'New York'],
    images: [
      'https://picsum.photos/800/600?random=13',
      'https://picsum.photos/800/600?random=14',
    ],
    basePrice: 2200,
    currency: 'EUR',
    description: 'Découvrez les lieux saints de Jérusalem : Via Dolorosa, Saint-Sépulcre, Mont des Oliviers, Bethléem, Nazareth, Lac de Tibériade. Un pèlerinage profondément spirituel sur les traces du Christ.',
    included: [
      'Hébergement en hôtel 4 étoiles à Jérusalem',
      'Tous les repas',
      'Guide spirituel francophone',
      'Visites guidées de tous les sites',
      'Transport privé',
      'Assurance voyage',
    ],
    notIncluded: [
      'Vols internationaux',
      'Pourboires',
    ],
    cancellationPolicy: 'Annulation gratuite jusqu\'à 45 jours avant le départ.',
    program: [
      {
        day: 1,
        title: 'Arrivée à Jérusalem',
        description: 'Accueil à l\'hôtel à Jérusalem. Réunion d\'information avec votre guide spirituel francophone. Première découverte de la Vieille Ville.',
        activities: ['Accueil et installation', 'Réunion d\'information', 'Découverte de la Vieille Ville', 'Temps libre', 'Dîner de bienvenue'],
        accommodation: 'Hôtel 4 étoiles à Jérusalem',
        meals: ['Dîner'],
        image: 'https://picsum.photos/800/600?random=501',
      },
      {
        day: 2,
        title: 'Mont des Oliviers et Gethsémani',
        description: 'Visite du Mont des Oliviers, de l\'église du Pater Noster, de l\'église de l\'Ascension, puis descente vers le Jardin de Gethsémani et l\'église de l\'Agonie.',
        activities: ['Mont des Oliviers', 'Église du Pater Noster', 'Jardin de Gethsémani', 'Église de l\'Agonie', 'Messe'],
        accommodation: 'Hôtel 4 étoiles à Jérusalem',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=502',
      },
      {
        day: 3,
        title: 'Via Dolorosa et Saint-Sépulcre',
        description: 'Parcours de la Via Dolorosa (Chemin de Croix) avec les 14 stations, arrivée au Saint-Sépulcre, visite de la basilique et des lieux saints.',
        activities: ['Via Dolorosa', '14 stations du Chemin de Croix', 'Saint-Sépulcre', 'Visite de la basilique', 'Messe'],
        accommodation: 'Hôtel 4 étoiles à Jérusalem',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=503',
      },
      {
        day: 4,
        title: 'Bethléem',
        description: 'Journée à Bethléem : visite de la Basilique de la Nativité, de la Grotte de la Nativité, et du Champ des Bergers.',
        activities: ['Basilique de la Nativité', 'Grotte de la Nativité', 'Champ des Bergers', 'Temps de prière', 'Messe'],
        accommodation: 'Hôtel 4 étoiles à Jérusalem',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=504',
      },
      {
        day: 5,
        title: 'Nazareth',
        description: 'Départ pour Nazareth, ville de l\'Annonciation. Visite de la Basilique de l\'Annonciation et de l\'église Saint-Joseph.',
        activities: ['Route vers Nazareth', 'Basilique de l\'Annonciation', 'Église Saint-Joseph', 'Découverte de Nazareth', 'Messe'],
        accommodation: 'Hôtel à Nazareth',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=505',
      },
      {
        day: 6,
        title: 'Lac de Tibériade et Capharnaüm',
        description: 'Visite du Lac de Tibériade, de Capharnaüm (ville de Jésus), de Tabgha (multiplication des pains) et du Mont des Béatitudes.',
        activities: ['Lac de Tibériade', 'Capharnaüm', 'Tabgha', 'Mont des Béatitudes', 'Messe'],
        accommodation: 'Hôtel au bord du Lac de Tibériade',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=506',
      },
      {
        day: 7,
        title: 'Cana et retour à Jérusalem',
        description: 'Visite de Cana (premier miracle de Jésus), puis retour vers Jérusalem. Temps libre dans la Vieille Ville.',
        activities: ['Cana', 'Retour à Jérusalem', 'Temps libre', 'Shopping', 'Messe'],
        accommodation: 'Hôtel 4 étoiles à Jérusalem',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=507',
      },
      {
        day: 8,
        title: 'Mont Sion et Cénacle',
        description: 'Visite du Mont Sion : Cénacle (Dernière Cène), église de la Dormition, tombe de David. Après-midi libre.',
        activities: ['Mont Sion', 'Cénacle', 'Église de la Dormition', 'Tombe de David', 'Messe'],
        accommodation: 'Hôtel 4 étoiles à Jérusalem',
        meals: ['Petit-déjeuner', 'Déjeuner libre', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=508',
      },
      {
        day: 9,
        title: 'Jéricho et Mer Morte',
        description: 'Excursion vers Jéricho, la plus ancienne ville du monde, puis baignade dans la Mer Morte.',
        activities: ['Route vers Jéricho', 'Visite de Jéricho', 'Mer Morte', 'Baignade', 'Retour à Jérusalem'],
        accommodation: 'Hôtel 4 étoiles à Jérusalem',
        meals: ['Petit-déjeuner', 'Déjeuner', 'Dîner'],
        image: 'https://picsum.photos/800/600?random=509',
      },
      {
        day: 10,
        title: 'Dernière visite et départ',
        description: 'Dernier temps de prière au Saint-Sépulcre, messe d\'action de grâce, puis transfert vers l\'aéroport pour le départ.',
        activities: ['Dernière visite Saint-Sépulcre', 'Messe d\'action de grâce', 'Temps libre', 'Transfert aéroport', 'Départ'],
        accommodation: 'N/A',
        meals: ['Petit-déjeuner'],
        image: 'https://picsum.photos/800/600?random=510',
      },
    ],
    sessions: [
      {
        id: 's10',
        startDate: format(addDays(nextMonth, 20), 'yyyy-MM-dd'),
        endDate: format(addDays(nextMonth, 30), 'yyyy-MM-dd'),
        price: 2200,
        currency: 'EUR',
        capacityTotal: 20,
        capacityRemaining: 10,
      },
      {
        id: 's11',
        startDate: format(addDays(threeMonthsLater, 5), 'yyyy-MM-dd'),
        endDate: format(addDays(threeMonthsLater, 15), 'yyyy-MM-dd'),
        price: 2300,
        currency: 'EUR',
        capacityTotal: 20,
        capacityRemaining: 20,
      },
    ],
  },
  {
    id: '8',
    slug: 'pelerinage-jerusalem-premium',
    title: 'Pèlerinage Terre Sainte - Expérience Premium',
    destination: 'Jérusalem',
    country: 'Israël',
    durationDays: 12,
    language: ['Français', 'Anglais'],
    status: 'SHOWCASE',
    departuresEligible: ['Paris', 'Londres', 'New York'],
    images: [
      'https://picsum.photos/800/600?random=15',
      'https://picsum.photos/800/600?random=16',
    ],
    basePrice: 3500,
    currency: 'EUR',
    description: 'Expérience de pèlerinage premium avec hébergement de luxe, repas gastronomiques, accès privé à certains sites, conférences avec théologiens, et temps de méditation personnalisé.',
    included: [
      'Hébergement en hôtel 5 étoiles',
      'Tous les repas gastronomiques',
      'Guide spirituel privé',
      'Accès VIP aux sites',
      'Conférences théologiques',
      'Transport privé de luxe',
    ],
    notIncluded: [
      'Vols internationaux',
      'Pourboires',
    ],
    cancellationPolicy: 'Sur demande - conditions à définir selon disponibilité.',
    sessions: [
      {
        id: 's12',
        startDate: format(addDays(threeMonthsLater, 10), 'yyyy-MM-dd'),
        endDate: format(addDays(threeMonthsLater, 22), 'yyyy-MM-dd'),
        price: 3500,
        currency: 'EUR',
        capacityTotal: 8,
        capacityRemaining: 8,
      },
    ],
  },
]
